import { generateNewUserData } from '../generateUser';
import {
  FIRST_NAME_ERROR_MESSAGE,
  LAST_NAME_ERROR_MESSAGE,
  ADDRESS_ERROR_MESSAGE,
  CITY_ERROR_MESSAGE,
  STATE_ERROR_MESSAGE,
  ZIP_CODE_ERROR_MESSAGE,
  SSN_ERROR_MESSAGE,
  USERNAME_ERROR_MESSAGE,
  PASSWORD_ERROR_MESSAGE,
  PASSWORD_CONFIRMATION_ERROR_MESSAGE
} from '../constants';

const user = generateNewUserData();

export const testParameters = [
  {
    title: 'empty first name',
    firstname: '',
    lastname: user.lastname,
    address: user.address,
    city: user.city,
    state: user.state,
    zip: user.zip,
    phone: user.phone,
    ssn: user.ssn,
    username: user.username,
    password: user.password,
    confirmPassword: user.password,
    expectedError: FIRST_NAME_ERROR_MESSAGE,
  },
  {
    title: 'empty last name',
    firstname: user.firstname,
    lastname: '',
    address: user.address,
    city: user.city,
    state: user.state,
    zip: user.zip,
    phone: user.phone,
    ssn: user.ssn,
    username: user.username,
    password: user.password,
    confirmPassword: user.password,
    expectedError: LAST_NAME_ERROR_MESSAGE,
  },
  {
    title: 'empty address',
    firstname: user.firstname,
    lastname: user.lastname,
    address: '',
    city: user.city,
    state: user.state,
    zip: user.zip,
    phone: user.phone,
    ssn: user.ssn,
    username: user.username,
    password: user.password,
    confirmPassword: user.password,
    expectedError: ADDRESS_ERROR_MESSAGE,
  },
  {
    title: 'empty city',
    firstname: user.firstname,
    lastname: user.lastname,
    address: user.address,
    city: '',
    state: user.state,
    zip: user.zip,
    phone: user.phone,
    ssn: user.ssn,
    username: user.username,
    password: user.password,
    confirmPassword: user.password,
    expectedError: CITY_ERROR_MESSAGE,
  },
  {
    title: 'empty state',
    firstname: user.firstname,
    lastname: user.lastname,
    address: user.address,
    city: user.city,
    state: '',
    zip: user.zip,
    phone: user.phone,
    ssn: user.ssn,
    username: user.username,
    password: user.password,
    confirmPassword: user.password,
    expectedError: STATE_ERROR_MESSAGE,
  },
  {
    title: 'empty zip code',
    firstname: user.firstname,
    lastname: user.lastname,
    address: user.address,
    city: user.city,
    state: user.state,
    zip: '',
    phone: user.phone,
    ssn: user.ssn,
    username: user.username,
    password: user.password,
    confirmPassword: user.password,
    expectedError: ZIP_CODE_ERROR_MESSAGE,
  },
  {
    title: 'empty ssn',
    firstname: user.firstname,
    lastname: user.lastname,
    address: user.address,
    city: user.city,
    state: user.state,
    zip: user.zip,
    phone: user.phone,
    ssn: '',
    username: user.username,
    password: user.password,
    confirmPassword: user.password,
    expectedError: SSN_ERROR_MESSAGE,
  },
  {
    title: 'empty username',
    firstname: user.firstname,
    lastname: user.lastname,
    address: user.address,
    city: user.city,
    state: user.state,
    zip: user.zip,
    phone: user.phone,
    ssn: user.ssn,
    username: '',
    password: user.password,
    confirmPassword: user.password,
    expectedError: USERNAME_ERROR_MESSAGE,
  },
  {
    title: 'empty password',
    firstname: user.firstname,
    lastname: user.lastname,
    address: user.address,
    city: user.city,
    state: user.state,
    zip: user.zip,
    phone: user.phone,
    ssn: user.ssn,
    username: user.username,
    password: '',
    confirmPassword: user.password,
    expectedError: PASSWORD_ERROR_MESSAGE,
    errorSelector: '#customer\\.password\\.errors',
  },
  {
    title: 'empty confirm password',
    firstname: user.firstname,
    lastname: user.lastname,
    address: user.address,
    city: user.city,
    state: user.state,
    zip: user.zip,
    phone: user.phone,
    ssn: user.ssn,
    username: user.username,
    password: user.password,
    confirmPassword: '',
    expectedError: PASSWORD_CONFIRMATION_ERROR_MESSAGE,
    errorSelector: '#repeatedPassword\\.errors',
  },
];
