import { generateNewUserData } from '../generateUser';
import {
  FIRST_NAME_ERROR_MESSAGE,
  LAST_NAME_ERROR_MESSAGE,
  ADDRESS_ERROR_MESSAGE,
  CITY_ERROR_MESSAGE,
  STATE_ERROR_MESSAGE,
  ZIP_CODE_ERROR_MESSAGE,
  SSN_ERROR_MESSAGE,
} from '../constants';

const user = generateNewUserData();

export const testParameters = [
  {
    title: 'empty first name',
    firstname: '',
    lastname: user.lastname,
    address: user.address,
    city: user.city,
    state: user.state,
    zip: user.zip,
    phone: user.phone,
    ssn: user.ssn,
    expectedError: FIRST_NAME_ERROR_MESSAGE,
  },
  {
    title: 'empty last name',
    firstname: user.firstname,
    lastname: '',
    address: user.address,
    city: user.city,
    state: user.state,
    zip: user.zip,
    phone: user.phone,
    ssn: user.ssn,
    confirmPassword: user.password,
    expectedError: LAST_NAME_ERROR_MESSAGE,
  },
  {
    title: 'empty address',
    firstname: user.firstname,
    lastname: user.lastname,
    address: '',
    city: user.city,
    state: user.state,
    zip: user.zip,
    phone: user.phone,
    ssn: user.ssn,
    username: user.username,
    password: user.password,
    confirmPassword: user.password,
    expectedError: ADDRESS_ERROR_MESSAGE,
  },
  {
    title: 'empty city',
    firstname: user.firstname,
    lastname: user.lastname,
    address: user.address,
    city: '',
    state: user.state,
    zip: user.zip,
    phone: user.phone,
    ssn: user.ssn,
    username: user.username,
    password: user.password,
    confirmPassword: user.password,
    expectedError: CITY_ERROR_MESSAGE,
  },
  {
    title: 'empty state',
    firstname: user.firstname,
    lastname: user.lastname,
    address: user.address,
    city: user.city,
    state: '',
    zip: user.zip,
    phone: user.phone,
    ssn: user.ssn,
    username: user.username,
    password: user.password,

    expectedError: STATE_ERROR_MESSAGE,
  },
  {
    title: 'empty zip code',
    firstname: user.firstname,
    lastname: user.lastname,
    address: user.address,
    city: user.city,
    state: user.state,
    zip: '',
    phone: user.phone,
    ssn: user.ssn,
    expectedError: ZIP_CODE_ERROR_MESSAGE,
  },
  {
    title: 'empty ssn',
    firstname: user.firstname,
    lastname: user.lastname,
    address: user.address,
    city: user.city,
    state: user.state,
    zip: user.zip,
    phone: user.phone,
    ssn: '',
    expectedError: SSN_ERROR_MESSAGE,
  }
]
